/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import ClassesAuxiliares.*;
import Controls.*;
import Models.*;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;



public class PrincipalView extends javax.swing.JFrame {

   private ControleProdutosControl produtoControl;
   private ProdutoModel produtoModel;
   Tabela tabela = new Tabela();
   private static Double subTotal = 0.0;
   private static Double total = 0.0;
   private OperadorControl operadorControl;
   private ProdutoModel produtoPesquisado;
   private ArrayList <ProdutoModel> array = new ArrayList<>();
   private static AtualizadorDeHorario ah;
   private int linha = 0;
   private int quant; 
    
    public PrincipalView() {
        initComponents();
         ah = new AtualizadorDeHorario(lbDate); 
         iniciaAtualizadorDeData();
         maximize();
         
         PesquisaClienteView pesquisa =  new PesquisaClienteView();
         pesquisa.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        painelPrincipal = new javax.swing.JPanel();
        painelDetalhesVenda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDetalhesVenda = new javax.swing.JTable();
        painelCalculo = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        painelPesquisaProdutos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtProdutos = new javax.swing.JTable();
        txtPesq = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        btnCancelarVenda = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblStatusCaixa = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        painelDeFerramentas = new javax.swing.JPanel();
        btnCadastrarProduto = new javax.swing.JButton();
        btnCadastrarCliente = new javax.swing.JButton();
        btnLocalizarCliente = new javax.swing.JButton();
        sep1 = new javax.swing.JSeparator();
        sep2 = new javax.swing.JSeparator();
        sep3 = new javax.swing.JSeparator();
        btnLocalizarCliente1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jmenuPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnSair = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(1024, 768));

        painelPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        painelPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelPrincipal.setPreferredSize(new java.awt.Dimension(1024, 768));

        painelDetalhesVenda.setBackground(new java.awt.Color(0, 51, 153));
        painelDetalhesVenda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes da Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        painelDetalhesVenda.setForeground(new java.awt.Color(102, 0, 0));

        jtDetalhesVenda.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtDetalhesVenda.setForeground(new java.awt.Color(51, 0, 204));
        jtDetalhesVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cód", "Produto", "Quant", "Preço Unitario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDetalhesVenda.setGridColor(new java.awt.Color(102, 102, 102));
        jtDetalhesVenda.setRowHeight(20);
        jScrollPane1.setViewportView(jtDetalhesVenda);
        if (jtDetalhesVenda.getColumnModel().getColumnCount() > 0) {
            jtDetalhesVenda.getColumnModel().getColumn(0).setMinWidth(35);
            jtDetalhesVenda.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtDetalhesVenda.getColumnModel().getColumn(1).setMinWidth(200);
            jtDetalhesVenda.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtDetalhesVenda.getColumnModel().getColumn(2).setMinWidth(40);
            jtDetalhesVenda.getColumnModel().getColumn(2).setPreferredWidth(40);
            jtDetalhesVenda.getColumnModel().getColumn(3).setResizable(false);
        }

        painelCalculo.setBackground(new java.awt.Color(0, 51, 153));
        painelCalculo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculo de venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        painelCalculo.setForeground(new java.awt.Color(255, 255, 0));

        lb1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 204, 0));
        lb1.setText("Subtotal - R$");

        lb2.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lb2.setForeground(new java.awt.Color(255, 255, 255));
        lb2.setText("Desconto - R$");

        lb3.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lb3.setForeground(new java.awt.Color(102, 255, 0));
        lb3.setText("TOTAL - R$");

        lblTotal.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(102, 255, 0));
        lblTotal.setText("00,00");

        lblDesc.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lblDesc.setForeground(new java.awt.Color(255, 255, 255));
        lblDesc.setText("00.00");

        lblSubtotal.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(255, 204, 0));
        lblSubtotal.setText("00,00");

        javax.swing.GroupLayout painelCalculoLayout = new javax.swing.GroupLayout(painelCalculo);
        painelCalculo.setLayout(painelCalculoLayout);
        painelCalculoLayout.setHorizontalGroup(
            painelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCalculoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(painelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb2)
                    .addComponent(lb3)
                    .addComponent(lb1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        painelCalculoLayout.setVerticalGroup(
            painelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCalculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb1)
                    .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lb3.getAccessibleContext().setAccessibleName("TOTAL R$");

        javax.swing.GroupLayout painelDetalhesVendaLayout = new javax.swing.GroupLayout(painelDetalhesVenda);
        painelDetalhesVenda.setLayout(painelDetalhesVendaLayout);
        painelDetalhesVendaLayout.setHorizontalGroup(
            painelDetalhesVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDetalhesVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDetalhesVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(painelCalculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelDetalhesVendaLayout.setVerticalGroup(
            painelDetalhesVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDetalhesVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelPesquisaProdutos.setBackground(new java.awt.Color(0, 51, 153));
        painelPesquisaProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        painelPesquisaProdutos.setForeground(new java.awt.Color(255, 255, 255));

        jtProdutos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtProdutos.setForeground(new java.awt.Color(51, 0, 204));
        jtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod", "Produto", "Detalhe", "Valor Unit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtProdutos.setRowHeight(20);
        jtProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtProdutos);
        if (jtProdutos.getColumnModel().getColumnCount() > 0) {
            jtProdutos.getColumnModel().getColumn(0).setMinWidth(40);
            jtProdutos.getColumnModel().getColumn(0).setPreferredWidth(40);
            jtProdutos.getColumnModel().getColumn(0).setMaxWidth(40);
            jtProdutos.getColumnModel().getColumn(1).setMinWidth(150);
            jtProdutos.getColumnModel().getColumn(1).setPreferredWidth(150);
            jtProdutos.getColumnModel().getColumn(1).setMaxWidth(150);
            jtProdutos.getColumnModel().getColumn(3).setMinWidth(70);
            jtProdutos.getColumnModel().getColumn(3).setPreferredWidth(70);
            jtProdutos.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        txtPesq.setBackground(new java.awt.Color(0, 0, 0));
        txtPesq.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtPesq.setForeground(new java.awt.Color(255, 255, 0));
        txtPesq.setToolTipText("Pesquisa");
        txtPesq.setCaretColor(new java.awt.Color(204, 204, 204));
        txtPesq.setMargin(new java.awt.Insets(10, 2, 2, 2));
        txtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqKeyReleased(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 102, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/finaliza_venda.png"))); // NOI18N
        jButton6.setText("Finalizar Venda");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCancelarVenda.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btnCancelarVenda.setForeground(new java.awt.Color(204, 0, 0));
        btnCancelarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancela_venda.png"))); // NOI18N
        btnCancelarVenda.setText("Cancelar Venda");
        btnCancelarVenda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelarVenda.setEnabled(false);
        btnCancelarVenda.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPesquisaProdutosLayout = new javax.swing.GroupLayout(painelPesquisaProdutos);
        painelPesquisaProdutos.setLayout(painelPesquisaProdutosLayout);
        painelPesquisaProdutosLayout.setHorizontalGroup(
            painelPesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPesquisaProdutosLayout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(btnCancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtPesq))
                .addContainerGap())
        );
        painelPesquisaProdutosLayout.setVerticalGroup(
            painelPesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaProdutosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(painelPesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarVenda))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status do Caixa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        lblStatusCaixa.setFont(new java.awt.Font("Arial Narrow", 1, 48)); // NOI18N
        lblStatusCaixa.setForeground(new java.awt.Color(51, 255, 51));
        lblStatusCaixa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatusCaixa.setText("LIVRE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStatusCaixa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(lblStatusCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelDetalhesVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(painelPesquisaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painelPesquisaProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(painelDetalhesVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98))
        );

        lbDate.setBackground(new java.awt.Color(0, 0, 0));
        lbDate.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lbDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbDate.setText("Sistema de Gerenciamento de Pizzaria - São Paulo, 07 de setembro de 2016 - 09:59:20");

        painelDeFerramentas.setBackground(new java.awt.Color(255, 255, 255));
        painelDeFerramentas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCadastrarProduto.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrarProduto.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnCadastrarProduto.setForeground(new java.awt.Color(153, 0, 51));
        btnCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastro_produto.png"))); // NOI18N
        btnCadastrarProduto.setText("Controle de Produtos");
        btnCadastrarProduto.setActionCommand("Produtos");
        btnCadastrarProduto.setBorder(null);
        btnCadastrarProduto.setFocusable(false);
        btnCadastrarProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrarProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        btnCadastrarCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrarCliente.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnCadastrarCliente.setForeground(new java.awt.Color(153, 0, 51));
        btnCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastro_cliente.png"))); // NOI18N
        btnCadastrarCliente.setText("Controle de  Clientes");
        btnCadastrarCliente.setBorder(null);
        btnCadastrarCliente.setFocusable(false);
        btnCadastrarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });

        btnLocalizarCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnLocalizarCliente.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnLocalizarCliente.setForeground(new java.awt.Color(153, 0, 51));
        btnLocalizarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisa_cliente.png"))); // NOI18N
        btnLocalizarCliente.setText("Localizar Cliente");
        btnLocalizarCliente.setActionCommand("Cadastrar Cliente");
        btnLocalizarCliente.setBorder(null);
        btnLocalizarCliente.setFocusable(false);
        btnLocalizarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLocalizarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        sep1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        sep2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        sep3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnLocalizarCliente1.setBackground(new java.awt.Color(255, 255, 255));
        btnLocalizarCliente1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnLocalizarCliente1.setForeground(new java.awt.Color(153, 0, 51));
        btnLocalizarCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pizza.png"))); // NOI18N
        btnLocalizarCliente1.setText("Controle de Pedidos");
        btnLocalizarCliente1.setActionCommand("Cadastrar Cliente");
        btnLocalizarCliente1.setBorder(null);
        btnLocalizarCliente1.setFocusable(false);
        btnLocalizarCliente1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLocalizarCliente1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout painelDeFerramentasLayout = new javax.swing.GroupLayout(painelDeFerramentas);
        painelDeFerramentas.setLayout(painelDeFerramentasLayout);
        painelDeFerramentasLayout.setHorizontalGroup(
            painelDeFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sep1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sep2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLocalizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sep3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLocalizarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelDeFerramentasLayout.setVerticalGroup(
            painelDeFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDeFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDeFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sep1)
                    .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadastrarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sep2)
                    .addComponent(btnLocalizarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sep3)
                    .addComponent(btnLocalizarCliente1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Operador : Roberto - Login em : 08/09/2016 - 13:17");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jmenuPrincipal.setBackground(new java.awt.Color(0, 0, 153));
        jmenuPrincipal.setBorder(new javax.swing.border.MatteBorder(null));
        jmenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jmenuPrincipal.setBorderPainted(false);
        jmenuPrincipal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Relatórios");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem2.setText("Financeiro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jmenuPrincipal.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Configurações");
        jMenu2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jmenuPrincipal.add(jMenu2);

        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Fazer Logout");
        btnSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        jmenuPrincipal.add(btnSair);

        setJMenuBar(jmenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(painelDeFerramentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelDeFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 522, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jSeparator3)))
        );

        jLabel3.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
            System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
       
        new ControleProdutosView().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void txtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqKeyReleased
        operadorControl = new OperadorControl();
        //LIMPA O ARRAY
        array.clear();

        //LIMPA A TABELA
        limparTabela(jtProdutos);

        //SOMENTE REALIZA A PESQUISA E A CAIXA DE PESQUISA TIVER VALOR
        if(!txtPesq.getText().equals("")){
            OperadorControl.pesq = txtPesq.getText();
            array = operadorControl.pesquisarProduto();
        }

        //RECUPERA OS OBJETOS RETORNADOS NA PESQUISA
        for (int x = 0 ; x < array.size(); x++){
            produtoPesquisado = (ProdutoModel) array.get(x);
            jtProdutos.setValueAt(produtoPesquisado.getIdProduto(), x, 0);
            jtProdutos.setValueAt(produtoPesquisado.getTipoProduto(), x, 1);
            jtProdutos.setValueAt(produtoPesquisado.getDetalheProduto(), x, 2);
            jtProdutos.setValueAt(produtoPesquisado.getValorUnitario(), x, 3);
        }
    }//GEN-LAST:event_txtPesqKeyReleased

    private void jtProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProdutosMouseClicked
                   
       if(!jtProdutos.getValueAt(jtProdutos.getSelectedRow(), 0).equals("")){
           
            try{
                quant = Integer.parseInt(JOptionPane.showInputDialog("Digite a Quantidade do Produto"));
                     if(quant < 1){
                             Msg.exclamation("Digite uma quantidade válida !");                          
                     }   
                     else{

                     if(!lblStatusCaixa.getText().equals("Realizando Venda")){
                     lblStatusCaixa.setText("Realizando Venda");
                     lblStatusCaixa.setForeground(Color.red);
                      btnCancelarVenda.setEnabled(true);
                     }    

                     Double valor = Double.parseDouble(jtProdutos.getValueAt(jtProdutos.getSelectedRow(), 3).toString()) * quant;

                     jtDetalhesVenda.setValueAt(jtProdutos.getValueAt(jtProdutos.getSelectedRow(), 0),linha, 0);
                     jtDetalhesVenda.setValueAt(jtProdutos.getValueAt(jtProdutos.getSelectedRow(), 1),linha, 1);
                     jtDetalhesVenda.setValueAt(quant,linha, 2);
                     jtDetalhesVenda.setValueAt(valor, linha, 3);  

                     subTotal += valor;
                     total = subTotal - (Double.parseDouble(lblDesc.getText()));

                     lblSubtotal.setText(subTotal.toString());
                     lblTotal.setText(total.toString());

                     linha++;
                     }
                }
            catch(NumberFormatException ex){
                Msg.exclamation("Digite uma quantidade Válida !");                                                                
            }
        }                         
    }//GEN-LAST:event_jtProdutosMouseClicked

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
         new PesquisaClienteView().setVisible(true);
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void btnCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVendaActionPerformed
        cancelarVenda();
    }//GEN-LAST:event_btnCancelarVendaActionPerformed

    
    
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           new PrincipalView().setVisible(true);                                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnCancelarVenda;
    private javax.swing.JButton btnLocalizarCliente;
    private javax.swing.JButton btnLocalizarCliente1;
    private javax.swing.JMenu btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JMenuBar jmenuPrincipal;
    private javax.swing.JTable jtDetalhesVenda;
    private javax.swing.JTable jtProdutos;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblStatusCaixa;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel painelCalculo;
    private javax.swing.JPanel painelDeFerramentas;
    private javax.swing.JPanel painelDetalhesVenda;
    private javax.swing.JPanel painelPesquisaProdutos;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JSeparator sep3;
    private javax.swing.JTextField txtPesq;
    // End of variables declaration//GEN-END:variables

    
    
  //ATUALIZA A HORA DO LABE 'LBDATA'  
 private void iniciaAtualizadorDeData(){
    ah.start();    
    }    
 
 
 
 //METODO PARA LIMPAR AS TABELAS
 private void limparTabela(JTable table) {
    for (int x = 0; x < table.getRowCount(); x++) {
        table.setValueAt("", x, 0);
        table.setValueAt("", x, 1);
        table.setValueAt("", x, 2);
    }
}
 
 //METODO PARA INICIAR O FORM MAXIMIZADO 
 private void maximize( ){
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
 }

 private void cancelarVenda(){
        Boolean retorno = Msg.question("Tem certeza que deseja Cancelar a Venda");
        if(retorno){
        subTotal = 0.0;
        total = 0.0;
        lblSubtotal.setText("0.00");
        lblDesc.setText("0.00"); 
        lblTotal.setText("0.00");       
        lblStatusCaixa.setText("Caixa Livre");
        txtPesq.setText("");
        lblStatusCaixa.setForeground(Color.green);        
        tabela.limparTabela(jtProdutos);        
        tabela.limparTabela(jtDetalhesVenda);
        btnCancelarVenda.setEnabled(false);
        Msg.confirm("Venda Cancelada !");       
    }            
 } 
 
}
